sudo: required
dist: xenial
language: bash
before_script:
- sudo apt-get update -qq
- sudo apt-get install aria2 zip unzip check gzip -qq
script:
- source ./env.sh
- "${DLR} ${ROOTFS_URL} -o ${ROOTFS_FN}"
- 
- sudo tar -zxpf ${ROOTFS_FN}
- sudo mount --bind root.x86_64 root.x86_64
- cd root.x86_64
- sudo cp -bf ../mirrorlist ./etc/pacman.d/mirrorlist
- sudo cp -bf ../mirrorlist-alter ./etc/pacman.d/mirrorlist-alter
- sudo cp -bf ../pacman.conf.nosig ./etc/pacman.conf
- sudo sed -i -e "s/#ja_JP.UTF-8/ja_JP.UTF-8/" ./etc/locale.gen
- echo "LANG=ja_JP.UTF-8" | sudo tee ./etc/locale.conf
- sudo ln -sf /etc/locale.conf ./etc/default/locale
- sudo cp -f /etc/resolv.conf ./etc/resolv.conf
- sudo mv -f ./etc/mtab ./etc/mtab.bak
- echo "rootfs / rootfs rw 0 0" | sudo tee ./etc/mtab
- 
- sudo mount -t proc proc proc/
- sudo mount --bind /sys sys
- yes | sudo chroot . /usr/bin/pacman -Sy 
- yes | sudo chroot . /usr/bin/pacman -S filesystem
- yes |sudo chroot . /usr/bin/pacman -Syu ${PAC_PKGS}
- echo sudo chmod u+s ./usr/bin/ping
- sudo rm -rf ./etc/mtab
- echo "rootfs / rootfs rw 0 0" | sudo tee ./etc/mtab
- sudo chroot . /usr/bin/locale-gen
- yes | sudo chroot . /usr/bin/pacman -Scc
- 
- sudo umount ./{sys,proc}
- sudo mv -f ./etc/mtab.bak ./etc/mtab
- sudo cp -f ../pacman.conf ./etc/pacman.conf
- echo "# This file was automatically generated by WSL. To stop automatic generation
  of this file, remove this line." | sudo tee ./etc/resolv.conf
- 
- sudo rm -rf `sudo find ./root/ -type f`
- sudo rm -rf `sudo find ./var/cache/pacman/pkg/ -type f`
- 
- sudo tar -zcpf ../rootfs.tar.gz *
- sudo chown `id -un` ../rootfs.tar.gz
- cd ..
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: KnQ/nYNPd2JJ1+lYxL8VdyzjzHcimMhOeLOCoZKYPhgj3I7li66kHoEJGUH6sTPGpLItVJ0ycVwlofHD8SQcSer59XmWEqneOPnC6nKtxCtHqLkNp5GsODuXV+ND9cTaLtAdz9+Rt4f1D+sg0luN+kV5kQSFhl0WQM3SmAFnwBaDkQMfWe0j2Rf18vMqFssqM9NouXLzqAZ5P+mt6jhiQbA87qECSs/uXwF+6MVq63LBR/WZJj/tjDcUg7pLorPhdtsuYP5W+6VdWGkC0/0LbtdANPdvjGP5lfLrpLOviw2CSQrQmJg36MyNh4MPiFTckGVcw8c8blUFW+awyQldgUg6UovSgOCfSJ+feqiTbvrz6UQEJ7Gd9uaXY2Mc5l4LJbB1ry0P7JS/RSy5EsuUy9zmjLQr+mLUK2X3okiTgzHSp2/cCpZH+aiAfLSR0G5skS9Royf69oX3+1ifKUgiIsEuQx9HKpCOt2Nx0Otx20gx7eStrckSCv5yjvQ33wAtmZ0ym/npvqsenNk7kOoto6xDIYmjEhvAa2xK8K0M/W38tPeTQ+zh+Vcs+TcsBAW+CpRT8HfaeqRBCrlIZa4SuKcZkf2I3BjclaGiBljNEBCWBIF1/o3qndWNtdIHaaDRTBUnYL7bSXaQt5mP82l/gmx1kpbU1EUL5Ihc4Lm1GKE=
  file: 'rootfs.tar.gz'
  on:
    repo: kokkiemouse/Alter-WSL-FS
    all_branches: true
  skip_cleanup: 'true'
